In [1]:
import numpy as np

a = [1,2,3,4,5,6,7,8,9]
A = np.array([1,2,3,4,5,6,7,8,9])

print(a)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [2]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [3]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [5]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [6]:
data = np.arange(0,10)
data.shape

(10,)

In [7]:
data.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
A.shape

(9,)

In [10]:
A.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
B = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
B.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
D = np.arange(1,10).reshape(3,3)
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
M = np.dot(D,I)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [21]:
sum_val = np.sum(M)
sum_val

45.0

In [22]:
np.sum(M,axis=1)

array([ 6., 15., 24.])

In [23]:
np.sum(M,axis=0)

array([12., 15., 18.])

In [24]:
A = [[2,3,4,
     5,6,7,
     8,9,10]]
np.sum(A)

54

In [27]:
A = [[2,3,4],
     [5,6,7],
     [8,9,10]]
np.sum(A, axis=1)

array([ 9, 18, 27])

In [28]:
A = [[2,3,4],
     [5,6,7],
     [8,9,10]]
np.sum(A, axis=0)

array([15, 18, 21])