In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_numpy_list = np.array(my_list)
my_numpy_list

array([1, 2, 3, 4, 5])

In [2]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [4]:
my_list = np.arange(10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_list = np.arange(0,10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_list = np.arange(0,11,2)
my_list

array([ 0,  2,  4,  6,  8, 10])

In [7]:
my_zeros = np.zeros(7)
my_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [8]:
my_ones = np.ones(5)
my_ones

array([1., 1., 1., 1., 1.])

In [9]:
two_d = np.zeros((3,5))
two_d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(1, 3, 15)

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])

In [11]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(4)

array([0.37871056, 0.43185745, 0.28646084, 0.9650595 ])

In [13]:
np.random.rand(4)

array([0.2450613 , 0.12735455, 0.88781725, 0.81683051])

In [14]:
np.random.rand(5, 4)

array([[0.44530486, 0.07208129, 0.20219762, 0.37689578],
       [0.07997644, 0.86845754, 0.70762787, 0.28048531],
       [0.2457733 , 0.08472661, 0.40644936, 0.84543211],
       [0.31704118, 0.86173361, 0.89126337, 0.61760704],
       [0.6151887 , 0.69481534, 0.43110647, 0.14319719]])

In [15]:
np.random.randn(7)

array([-0.90874053, -0.8909069 , -0.3400286 , -0.63526487,  1.22912702,
        1.30359482, -1.60305692])

In [16]:
np.random.randn(3,5)

array([[ 0.24225471,  0.62724081, -0.08186708, -0.79980036,  1.65809749],
       [ 0.4915936 , -0.51779744,  1.03855517,  1.46596617,  1.30303335],
       [ 0.38468901, -0.93089581, -0.70107619,  0.37142716,  0.6258329 ]])

In [18]:
np.random.randint(20)

3

In [19]:
np.random.randint(2, 20)

6

In [20]:
np.random.randint(2, 20, 7)

array([18, 12, 14,  9,  3, 17, 19])

In [26]:
arr = np.random.rand(25)
arr

array([0.86483486, 0.46755172, 0.2359858 , 0.86653165, 0.55738913,
       0.96833207, 0.05890546, 0.15385441, 0.26792453, 0.22549919,
       0.99990737, 0.42650839, 0.85695799, 0.71871047, 0.66598888,
       0.58468306, 0.98685014, 0.17339582, 0.29188644, 0.81447934,
       0.55275545, 0.92621592, 0.61568969, 0.66828358, 0.37719928])

In [27]:
arr.reshape(5,5)

array([[0.86483486, 0.46755172, 0.2359858 , 0.86653165, 0.55738913],
       [0.96833207, 0.05890546, 0.15385441, 0.26792453, 0.22549919],
       [0.99990737, 0.42650839, 0.85695799, 0.71871047, 0.66598888],
       [0.58468306, 0.98685014, 0.17339582, 0.29188644, 0.81447934],
       [0.55275545, 0.92621592, 0.61568969, 0.66828358, 0.37719928]])

In [30]:
arr_2 = np.random.randint(0, 20, 10) 
arr_2

array([15, 19, 13,  2,  5, 14, 18, 14, 14, 14])

In [31]:
arr_2.max()

19

In [32]:
arr_2.min()

2

In [33]:
arr_2.argmax()

1

In [34]:
arr_2.argmin()

3

In [35]:
arr.shape

(25,)

In [36]:
my_array = np.arange(0,11)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
my_array[8]

8

In [38]:
my_array[2:6]

array([2, 3, 4, 5])

In [39]:
my_array[:6] 

array([0, 1, 2, 3, 4, 5])

In [40]:
my_array[5:]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
new_arr = np.arange(5,15)
new_arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
new_arr > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [43]:
bool_arr = new_arr > 10
new_arr[bool_arr]

array([11, 12, 13, 14])

In [44]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr * arr 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [46]:
arr + 50 

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [47]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [48]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
mat.sum()

325

In [50]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [51]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])